config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}
  
  resources :users, only: [:show, :update] do
    resources :requests, only: [:create, :update, :destroy] do
      collection do
        get 'create'
      end
    end
  end
  
  resources :workplaces do
    resources :shifts, except: [:show, :edit] do
      member do
        get 'trade'
        post 'trade_request'
      end
    end
  end
  resources :user_workplaces, only: [:create, :update, :destroy]
  
  post 'workplaces' => 'workplaces#create'
  
  as :user do
    get '/sign_in' => 'devise/sessions#new'
    get '/sign_up' => 'devise/registrations#new'
  end
  
  authenticated :user do
    root to: 'users#show', as: 'authenticated_root'
  end
  
  root to: 'welcome#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable, :confirmable,
  :omniauthable, omniauth_providers: [:facebook]
  
  has_many :user_workplaces, dependent: :destroy
  has_many :workplaces, through: :user_workplaces
  has_many :shifts
    
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email       = auth.info.email
      user.password    = Devise.friendly_token[0,20]
      user.name        = auth.info.name
      user.skip_confirmation!
    end
  end
  
  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session['devise.facebook_data'] && session['devise.facebook_data']['extra']['raw_info']
        user.email = data['email'] if user.email.blank?
      end
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env['omniauth.auth'])
    
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
    
    if request.env["omniauth.auth"].info.email.blank?
      redirect_to "/users/auth/facebook?auth_type=rerequest&scope=email"
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = current_user
    @user_workplaces = @user.user_workplaces.all
    @available_shifts = Shift.where(user_name: current_user.name, accepted: false)
    @accepted_shifts = Shift.where(user_name: current_user.name, accepted: true)
    @user_requests = Request.where(user_id: current_user.id, accepted: false)
    @coworker_requests = Request.where(coworker_id: current_user.id, accepted: false)
  end
  
  def update
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.haml
- if @user_workplaces.none?
  .col-md-12.text-center
    %h2
      %br
      %br
      Hi there! Let's find your workplace.
      %br
      %br
      = render 'workplaces/search'

.col-md-12.text-center
  - if @user_workplaces.any?
    %h2 My Workplaces
    %br
    - @user_workplaces.each do |workplace|
      = link_to workplace.name, workplace_path(workplace.workplace_id), class: 'btn btn-primary'
    %br
    %br
    = link_to "Find another workplace", workplaces_path, class: 'btn btn-info'
    %br
    - if @user_requests.any? || @coworker_requests.any?
      %h2 My Shift Trade Requests
      - @user_requests.each do |shift|
        %h4
          Your request to trade your
          %br
          = Shift.find(shift.user_shift).name
          shift on
          %br
          = Shift.find(shift.user_shift).date.strftime("%A, %m/%d/%Y")
          %br
          is still pending approval.
          %br
          %br
          You will be notified by email when it has been approved or rejected.
          %br
      - @coworker_requests.each do |shift|
        %h4
          = User.find(shift.user_id).name
          wants to trade their
          %br
          %br
          = Shift.find(shift.user_shift).name
          shift
          %br
          = Shift.find(shift.user_shift).date.strftime("%A, %m/%d/%Y")
          %br
          = Shift.find(shift.user_shift).start.strftime("%l:%M %p")
          to
          = Shift.find(shift.user_shift).finish.strftime("%l:%M %p")
          %br
          %br
          for your
          %br
          %br
          = Shift.find(shift.coworker_shift).name
          shift
          %br
          = Shift.find(shift.coworker_shift).date.strftime("%A, %m/%d/%Y")
          %br
          = Shift.find(shift.coworker_shift).start.strftime("%l:%M %p")
          to
          = Shift.find(shift.coworker_shift).finish.strftime("%l:%M %p")
          %br
          %br
          = link_to "Accept", user_request_path(@user, shift), class: 'btn btn-primary', method: :patch
          = link_to "Deny", user_request_path(@user, shift), class: 'btn btn-warning', method: :delete
          %br
    %h2 My Available Shifts
    %br
    - @available_shifts.each do |shift|
      .btn-group{role: "group"}
        .btn.btn-default
          %p
            = Workplace.find(shift.workplace_id).name
            %br
            = shift.name
            shift
            %br
            = shift.date.strftime("%A, %m/%d/%Y")
            %br
            = shift.start.strftime("%l:%M %p")
            to
            = shift.finish.strftime("%l:%M %p")
            %br
            = link_to "Delete", workplace_shift_path(Workplace.find(shift.workplace_id).name, shift), class: 'btn btn-danger', method: :delete
    %br
    %br
    %h2 My Accepted Shifts
    %br
    - @accepted_shifts.each do |shift|
      .btn-group{role: "group"}
        .btn.btn-default
          %p
            = Workplace.find(shift.workplace_id).name
            %br
            = shift.name
            shift
            %br
            = shift.date.strftime("%A, %m/%d/%Y")
            %br
            = shift.start.strftime("%l:%M %p")
            to
            = shift.finish.strftime("%l:%M %p")
            %br
            = link_to "Delete", workplace_shift_path(Workplace.find(shift.workplace_id).name, shift), class: 'btn btn-danger', method: :delete
    %br
    %br
    