config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}
  
  resources :users, only: [:show, :update] do
    resources :requests, only: [:create, :update, :destroy] do
      collection do
        get 'create'
      end
    end
  end
  
  resources :workplaces do
    resources :shifts, except: [:show, :edit] do
      member do
        get 'trade'
        post 'trade_request'
      end
    end
  end
  resources :user_workplaces, only: [:create, :update, :destroy]
  
  post 'workplaces' => 'workplaces#create'
  
  as :user do
    get '/sign_in' => 'devise/sessions#new'
    get '/sign_up' => 'devise/registrations#new'
  end
  
  authenticated :user do
    root to: 'users#show', as: 'authenticated_root'
  end
  
  root to: 'welcome#index'
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.haml
#headerwrap
  .container
    .row
      .col-lg-6.text-center
        %h1.title
          TradeMe
        %h2
          Connect.
          %br/
          Trade Shifts.
          %br/
          No Hassles.
        = link_to 'Sign Up Today!', sign_up_path, class: 'btn btn-warning btn-lg'
      .col-lg-6
        = image_tag("screenshot.png", height: '480', class: 'img-responsive')
        
         
#features
.container
  .row.mt.centered
    .col-lg-6.col-lg-offset-3
      %h1
        Trading Shifts
        %br>/
        Made Easy
      %h3 Many businesses lack a scheduling system that handles shift trades. TradeMe provides an easy-to-use solution for co-workers to trade their shifts.
  .row.mt.centered
    .col-lg-4
      %i.fa.fa-apple.fa-5x
      %i.fa.fa-android.fa-5x
      %i.fa.fa-windows.fa-5x
      %br
      %br
      %h4 Cross-Platform Compatibility
      %p TradeMe was built from the ground up to be a full-featured webapp that works on all major web browsers, as well as iOS, Android, and Windows Phone. 
    .col-lg-4
      %i.fa.fa-users.fa-5x
      %br
      %br
      %h4 One Site, One Solution
      %p No more private Facebook groups or annoying group texts. Any employee with access to a web browser can login, submit, view, trade, and accept shift requests. Users can also receive email alerts to make it even easier to keep track of shift trades.
    .col-lg-4
      %i.fa.fa-usd.fa-5x
      %br
      %br
      %h4 Totally Free
      %p TradeMe is 100% free to use. Additional paid features may be added over time, but the core site will always be completely free.
.container
  %hr/
#about
.container
  .row.mt.centered
    .col-lg-6.col-lg-offset-3
      %h1
        About TradeMe
      %h3 TradeMe was designed and built by Austin Sisson as a final project for a full-stack web development bootcamp.
  .row.mt.centered
    .col-lg-12
      = image_tag("me.png", class: 'img img-circle', height: '100')
      %h4 Austin Sisson
      %p Hey there! I built this app with restaurant servers and bartenders in mind, but I think it can be applied to any industry where employees frequently trade shifts. TradeMe is a work in progress, and I would love to hear what you think about it!
      %a{:href => "mailto:austin@trademe.io"}
        %button.btn.btn-default{:type => "button"} Email me!
.container
  %hr/
  %p.attribution.centered Built using a modified theme originally created by BlackTie.co - Attribution License 3.0 - 2013