config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}
  
  resources :users, only: [:show, :update] do
    resources :requests, only: [:create, :update, :destroy] do
      collection do
        get 'create'
      end
    end
  end
  
  resources :workplaces do
    resources :shifts, except: [:show, :edit] do
      member do
        get 'trade'
        post 'trade_request'
      end
    end
  end
  resources :user_workplaces, only: [:create, :update, :destroy]
  
  post 'workplaces' => 'workplaces#create'
  
  as :user do
    get '/sign_in' => 'devise/sessions#new'
    get '/sign_up' => 'devise/registrations#new'
  end
  
  authenticated :user do
    root to: 'users#show', as: 'authenticated_root'
  end
  
  root to: 'welcome#index'
end

app/models/workplace.rb
class Workplace < ActiveRecord::Base
  extend Textacular  
  validates_presence_of :name, :address, :city, :state, message: 'Oops, looks like you left a box blank!'
  validates_uniqueness_of :name, scope: :address, message: 'This workplace already exists!'
end

app/controllers/workplaces_controller.rb
class WorkplacesController < ApplicationController
  
  before_action :authenticate_user!, except: [:index]
  
  def index
    @workplaces = Workplace.fuzzy_search(name: params[:name], city: params[:city])
  end
  
  def show
    @workplace = Workplace.find(params[:id])
    @user = current_user.user_workplaces.where(workplace: @workplace).first
    @pending_users = User.find(UserWorkplace.where(workplace: @workplace, pending: true).pluck(:user_id))
    @shifts = Shift.where(workplace_id: @workplace, accepted: false)
  end
  
  def new
    @workplace = Workplace.new
  end
  
  def create
    @workplace = Workplace.create(workplace_params)
    
    if @workplace.save
      UserWorkplace.create(user: current_user, workplace: @workplace, pending: false, role: 'moderator')
      redirect_to workplace_path(@workplace)
      flash[:notice] = 'Workplace added!'
    else
      redirect_to new_workplace_path
      flash[:error] = @workplace.errors[:name].first
    end
  end
  
  def destroy
  end
  
  def update
  end
    
  private
  
  def workplace_params
    params.require(:workplace).permit(:name, :address, :city, :state)
  end
end

app/helpers/workplaces_helper.rb
module WorkplacesHelper
end

app/views/workplaces/_new_workplace.html.haml
= form_for @workplace do |f|
  .field
    = f.label :name
    %br
    = f.text_field :name
  .field
    = f.label :address
    %br
    = f.text_field :address
  .field
    = f.label :city
    %br
    = f.text_field :city
  .field
    = f.label :state
    %br
    = f.select :state, options_for_select(us_states)
  .field
    %br
    = f.submit "Add this workplace", class: 'btn btn-default'

app/views/workplaces/_search.html.haml
= form_tag workplaces_path, method: :get, class: 'form-inline' do
  .form-group
    = text_field_tag 'name', params[:name], placeholder: 'Workplace'
    = text_field_tag 'city', params[:city], placeholder: 'City'
    %br
    %br
    = submit_tag 'Search', class: 'btn btn-default btn-lg'

app/views/workplaces/index.html.haml
.results
.col-md-6.text-center
  - @workplaces.each do |workplace|
    %h2
      = workplace.name
      %br
        = workplace.address
      = "#{workplace.city + ', ' + workplace.state}"
    %br
    = link_to 'Join it!', user_workplaces_path(workplace_id: workplace.id), method: :post, class: 'btn btn-default btn-lg'
    %br
    %br
  - if @workplaces.none?
    %h2.text-center No workplaces match your search. 
    %br
.col-md-6.text-center  
  %h2
    Don't see your workplace?
    %br
    %br
    = link_to 'Add it!', new_workplace_path, class: 'btn btn-default btn-lg'
    %br
    %br
    Or
  %h3
    Look again
    %br
    %br
    = render 'search'


    

app/views/workplaces/new.html.haml
.col-md-12.text-center
  %h2 
    Add a new workplace
    %br
  = render 'new_workplace'

app/views/workplaces/show.html.haml
.col-md-12.text-center
  %h1
    = @workplace.name
  %p
    = @workplace.address
    = "#{@workplace.city + ', ' + @workplace.state}"
  %br
  %br

- unless @pending_users.include?(current_user)
  .col-md-12.text-center
    %h2 Available Shifts
    - @shifts.each do |shift|
      .btn-group{role: "group"}
        .btn.btn-default
          %p
            = "#{shift.user_name}'s"
            %br
            = shift.name
            shift
            %br
            = shift.date.strftime("%A, %m/%d/%Y")
            %br
            = shift.start.strftime("%l:%M %p")
            to
            = shift.finish.strftime("%l:%M %p")
      %br
      %br
      - unless shift.user_name == current_user.name
        = link_to "Accept Shift", workplace_shift_path(@workplace, shift, shift: {user_name: current_user.name, accepted: true, date: shift.date, name: shift.name}), method: :patch, class: 'btn btn-success',  data: {confirm: "Are you sure you want to accept this shift?"}
        = link_to "Ask to Trade", trade_workplace_shift_path(@workplace, shift), class: 'btn btn-info'
        %br
      %br
    - if @shifts.any?
      = link_to "Post new shift", new_workplace_shift_path(@workplace), class: 'btn btn-primary'
    - if @shifts.none?
      %h3 No shifts available?
      = link_to "Post new shift", new_workplace_shift_path(@workplace), class: 'btn btn-primary'

.col-md-12.text-center
  - if @pending_users.include?(current_user)
    %h2 Your request to join has been submitted. You will receive an email once a co-worker approves you.
    
  - if @user.moderator? && @pending_users.any?
    %h2 Approve New Co-Workers
    - @pending_users.each do |pending|
      = pending.name
      %br
      = pending.email
      %br
      - pending.user_workplaces.where(workplace: @workplace).each do |pending_id|
        = link_to "Approve", user_workplace_path(pending_id, user_workplace: { pending: false }), method: :put
        = link_to "Deny", user_workplace_path(pending_id), method: :delete
  