config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}
  
  resources :users, only: [:show, :update] do
    resources :requests, only: [:create, :update, :destroy] do
      collection do
        get 'create'
      end
    end
  end
  
  resources :workplaces do
    resources :shifts, except: [:show, :edit] do
      member do
        get 'trade'
        post 'trade_request'
      end
    end
  end
  resources :user_workplaces, only: [:create, :update, :destroy]
  
  post 'workplaces' => 'workplaces#create'
  
  as :user do
    get '/sign_in' => 'devise/sessions#new'
    get '/sign_up' => 'devise/registrations#new'
  end
  
  authenticated :user do
    root to: 'users#show', as: 'authenticated_root'
  end
  
  root to: 'welcome#index'
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}
    %title TradeMe
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = stylesheet_link_tag    'application', "http://fonts.googleapis.com/css?family=Lato:300,400,900"
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .navbar.navbar-default.navbar-fixed-top
      .flash
        - if flash[:notice]
          .alert.alert-success
            = flash[:notice]
        - elsif flash[:error]
          .alert.alert-danger
            = flash[:error]
        - elsif flash[:alert]
          .alert.alert-warning
            = flash[:alert]
      .container
        .navbar-header
          %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to "TradeMe", root_path, class: 'navbar-brand'
        .navbar-collapse.collapse
          %ul.nav.navbar-nav.navbar-right
            - if current_user.present?
              %li
                = link_to "Log Out", destroy_user_session_path, method: :delete
            - else
              %li
                = link_to 'Features', '/#features'
              %li
                = link_to 'About', '/#about'
              %li
                = link_to 'Sign In', sign_in_path
    = yield